handle_emergency_report:
  description: >
    Process the emergency report provided in the MD file located at {emergency_report}.
    This task involves reading, analyzing, and categorizing the data into structured sections
    for the Medical, Police, and Fire crews. The output must be a well-structured instance 
    of GeneralIncidenceReport, containing relevant information for each crew. If no injuries
    are reported, the IncidenceMedicalReport section will be omitted. The task ensures 
    data is classified accurately and sanitized for use in subsequent processing.
  steps: >
    1. Read and parse the emergency report using the ReadEmergencyReport tool.
       - The input for this tool is the JSON file located at {emergency_report}.
       - Ensure the file is fully read and converted into a structured format.
    2. Sanitize the parsed data:
       - Remove unwanted characters such as "\\" or "/" from all dictionary elements to ensure compatibility
         with tools and structured outputs.
    3. Classify the information by crew (Medical, Police, Fire):
       - Use the CraftGeneralIncidenceReport tool to analyze and categorize the data.
       - Populate the fields for IncidenceMedicalReport, IncidencePoliceReport, and IncidenceFireReport
         with the relevant details extracted from the emergency report.
       - If no injuries are reported, omit the IncidenceMedicalReport section.
    4. Construct the GeneralIncidenceReport:
       - Combine the structured data for each crew into a single instance of GeneralIncidenceReport.
       - Ensure that:
         - `medical` includes an IncidenceMedicalReport if applicable.
         - `fire` includes an IncidenceFireReport with fire-related details.
         - `police` includes an IncidencePoliceReport with law enforcement-related data.
    5. Return the completed GeneralIncidenceReport:
       - Ensure the report includes all applicable sections and is ready for further processing. For the final answer don't modify anything, just return the GeneralIncidenceReport.
  expected_output: >
    A structured instance of GeneralIncidenceReport that includes the following:
      - IncidenceMedicalReport: Details of medical incidents, if injuries are reported.
      - IncidencePoliceReport: Information for law enforcement and crowd management.
      - IncidenceFireReport: Details about fire-related incidents and required actions.
    If no data is applicable for a specific crew (e.g., no injuries), the corresponding section
    should be omitted to ensure relevance and conciseness.
  schema: GeneralIncidenceReport
  agent: dispatcher
