handle_medical_report:
  description: >
    Manage the report related to the Medical crew by coordinating with the Ambulance technician.
  steps: >
    1. Read Dispatcher Pydantic output for the Medical crew.  
    2. Based on their medical knowledge, assess the situation.  
    3. Contact the Ambulance technician with conclusions to ask for resource allocation.
  expected_output: >
    An assessment report and resource allocation request sent to the Ambulance technician, ready for crafting the action plan.
  schema:
    agent: doctor

craft_medical_action_plan:
  description: >
    Develop the Medical section of the action plan based on inputs from the Ambulance technician.
  steps: >
    1. Listen to the proposal of the Ambulance technician.  
    2. Create the Medical section of the action plan.  
    3. Report the Medical action plan to the Dispatcher.
  expected_output: >
    A detailed Medical section of the action plan, validated and ready for submission to the Dispatcher.
  schema:
    agent: doctor

allocate_medical_resources:
  description: >
    Determine and allocate the necessary medical resources for the situation.
  steps: >
    1. Receive the recommendation from the Doctor.  
    2. Read available medical resources.  
    3. Decide which resources (ambulances, types, drugs, personnel) should be sent, including computing distances between the scene and the resource locations.  
    4. Send the final decision back to the Doctor.
  expected_output: >
    A list of medical resources and their deployment plan, sent to the Doctor.
  schema:
    agent: ambulance_technician