handle_police_report:
  description: >
    Manage the report related to the Police crew by coordinating with the Allocator.
  steps: >
    1. Read Dispatcher Pydantic output for the Police crew.  
    2. Based on their knowledge, assess the situation.  
    3. Contact the Allocator with conclusions to ask for resource allocation.  
    4. Execute the Block streets task while waiting for the Allocator's response.
  expected_output: >
    An assessment report and resource allocation request sent to the Allocator, including preliminary street block information.
  schema:
  agent: police

block_streets:
  description: >
    Identify and include information about adjacent streets to be blocked and suggest alternative routes.
  steps: >
    1. Identify adjacent streets that need to be blocked.  
    2. Include the blocked streets and alternative routes in the final action plan.
  expected_output: >
    A detailed list of blocked streets and alternative routes to be included in the action plan.
  schema:
  agent: police

craft_police_action_plan:
  description: >
    Develop the Police section of the action plan based on inputs from the Allocator and street blocking details.
  steps: >
    1. Listen to the proposal of the Allocator.  
    2. Create the Police section of the action plan.  
    3. Report the Police action plan to the Dispatcher.
  expected_output: >
    A detailed Police section of the action plan, validated and ready for submission to the Dispatcher.
  agent: police

allocate_police_resources:
  description: >
    Determine and allocate the necessary police resources for the situation.
  steps: >
    1. Receive the recommendation from the General Purpose Police.  
    2. Read available police resources from {police_resources} JSON file.  
    3. Decide which resources (cars, guns, fences) should be sent, including computing distances between the scene and the resource locations.  
    4. Send the final decision back to the General Purpose Police.
  expected_output: >
    A list of police resources and their deployment plan, sent to the General Purpose Police.
  agent: allocator
